# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g07eQ9CbBBBlOEcybGfXIw81jm1LGDer
"""

#size
import numpy as np
arr=np.array([[1,3,5],[6,9,8,]])
print(arr.size)

#ndim
import numpy as np
arr_1d=np.array([1,2,3])
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)



#shape
import numpy as np
arr=np.array([[1,2,3,4,5],
             [1,6,7,8,9]])
print(arr.shape)

#dtype
import numpy as np
arr=np.array([10,45,67,20.8])
print(arr.dtype)

#astype
import numpy as np
arr=np.array([10,45.0,67.5,20.8])
print(arr.astype(int))

#Aggregate Function
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))

#Mathematical Operation
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr+5)
print(arr-5)
print(arr*5)
print(arr/5)
print(arr%5)
print(arr**5)

